export const categories = ["Opera", "Concert", "Theater Play", "Exhibition"];

export const demoResponse = {
  total_results: 242,
  total_pages: 25,
  current_page: 5,
  per_page: 10,
  offset: 40,
  sort_by: "start_datetime",
  direction: "asc",
  records: [
    {
      id: 64,
      name: 'otvorenje izložbe "Jaslice pod zvijezdama"',
      category: "Muzeji",
      location: null,
      description:
        "U petak, 29. studenoga 2024. u 18 sati, u Muzeju grada Zagreba bit će otvorena izložba jaslica, koju pripremamo u partnerstvu sa Udrugom prijatelja hrvatski božićnih jaslica, koja ove godine slavi 20. obljetnicu osnutka. Izložba će biti otvorena u predvorju Muzeja tijekom cijelog Adventa, a posjetitelji će je moći pogledati besplatno, do 5. siječnja 2025. godine.\nOtvorenje izložbe biranim će božićnim pjesmama obogatiti koncert SKUD-a Ivan Goran Kovačić. \n",
      start_datetime: "2024-11-29T17:00:00.000Z",
      end_datetime: null,
      price: "0.0",
      kid_friendly: true,
      event_url: null,
      created_at: "2024-11-23T18:08:23.547Z",
      updated_at: "2024-11-23T18:08:23.547Z",
      airtable_id: "recI1qxWXHoN4t25W",
      image_url: null,
    },
    {
      id: 148,
      name: "Božićna želja",
      category: "Kazalište",
      location: null,
      description:
        "Poetična obiteljska priča prožeta božićnim duhom govori o pravim vrijednostima u životu, ljubavi, zajedništvu i prijateljstvu.\n\nDora (8) i Luka (15) su brat i sestra koje žive s tatom i mamom koji “non-stop” rade, sužbeno putuju ili su na telefonu. Luka je u pubertetu i ne zanima ga ništa osim blagodati 21. stoljeća: interneta, fejsa, twittera, instagrama.. Sanja o pjevačkoj karijeri. Dora je usamljena i u školi i kod kuće, te uoči Božića sanja svoje prijatelje vile i vilenjake u nadi da će joj pomoći barem jedan dan u godini, na Božić, okupiti obitelj, kako sama kaže, oko “okićenog” bora ispod kojeg ne mora biti ni jedan jedini dar za nju, osim tate, mame i Luke. U zbrci tatinih telefonskih poziva, maminih otkazanih letova, svađica između Luke i Dore, isprepliću se sjećanja na neka druga vremena kada je obitelj bila zajedno, na dan kada je Dora kao zamotuljak stigla kući iz bolnice, na igre brata i sestre koja je ispunjavala kuću veselim smijehom.\n\nHoće li se Dorina obitelj okupiti ovoga Božića ispred okićenoga bora? Hoće li tinejdžer Luka potajno priznati da mu je omiljeni film Sam u kući i da postoji Djed Mraz preostaje Vam da otkrijete u našoj predstavi koja će razveseliti djecu, a roditelje ponovno vratiti u mladost i prisjetiti što znači pravi BOŽIĆ!\n",
      start_datetime: "2024-12-01T10:00:00.000Z",
      end_datetime: "2024-12-01T10:50:00.000Z",
      price: "600.0",
      kid_friendly: true,
      event_url: "https://zar-ptica.hr/predstava/predstave/bozicna-zelja/",
      created_at: "2024-11-23T18:08:24.586Z",
      updated_at: "2024-11-24T08:33:44.729Z",
      airtable_id: "recdBQcT69UZaZvSu",
      image_url:
        "https://v5.airtableusercontent.com/v3/u/35/35/1732449600000/Kl96tqX-M-C4FKgpYfkU3g/f58iV0Ug9w2yunwBaQzuLsb_JZAfBtwDw-GVg7rJFC9RcWIIuwP-V4R80J40aeaUd8cEqzpt8cDhFWLZfukgpyiN7-AZIR-EaQM93cnMwjdx2eiVCZZV2F6yi-yxIWUb_Blm6nfA3LwKARFPhjdp3A/PPISjUwHSy6N7LQBMExG9UqNzEwuCIZy6XI92P9T01s",
    },
    {
      id: 200,
      name: "Božić",
      category: "Razno",
      location: "Knjižnica Staglišće, A. Prosenika 7",
      description:
        "Izložba knjiga iz fonda knjižnice, tematski vezanih uz Božić.\n",
      start_datetime: "2024-12-01T13:00:00.000Z",
      end_datetime: "2025-01-06T13:00:00.000Z",
      price: null,
      kid_friendly: true,
      event_url: null,
      created_at: "2024-11-23T18:08:25.040Z",
      updated_at: "2024-11-23T18:08:25.040Z",
      airtable_id: "recn6Gtjs0KGjf4NO",
      image_url: null,
    },
    {
      id: 47,
      name: "Sv.Nikola",
      category: "Kazalište",
      location: "Park Stara Trešnjevka 1, Zageb",
      description:
        "Ne propustite pogledati predstavu Kazališta Prijatelj u kojoj vještica Zloćkoslava pokušava ukrasti Božić. U božićno vrijeme, kao što svi vrlo dobro znamo, Sveti Nikola luta svijetom i razveseljava djecu pričom i poklonima. Ponekad malo zaluta, ode na krivi kontinent, ali na kraju uvijek uspije svima donijeti radost i veselje. Ovaj put, u ovoj predstavi, naletjet će na opasnog neprijatelja – Zloćkoslavu. Ona se ne zadovoljava jednim poklonom, ona hoće sve poklone koje Sveti Nikola donosi dobroj djeci diljem svijeta. Ali, naravno, božićna predstava mora završiti sretno. Zato se pojavljuje dječak Milivoj Štreber koji će imati hrabrosti suprotstaviti se Zloćkoslavi i pobijediti njezino čaranje. On će ne samo uspjeti osloboditi Svetog Nikolu, već će i Zloćkicu uvjeriti da smisao Božića nije u gomilanju poklona nego u ozračju dobrote i mira koju on donosi u naša srca.\nPredstava se odvija u sklopu programa **Kazalište za sve** te s toga ima promotivnu cijenu ulaznice. Predstava je za djecu stariju od 3 godine.\n \n",
      start_datetime: "2024-12-05T17:00:00.000Z",
      end_datetime: "2024-12-05T17:30:00.000Z",
      price: "3.95",
      kid_friendly: true,
      event_url: "https://cekate.hr/program/sveti-nikola-i-zlockoslava/",
      created_at: "2024-11-23T18:08:23.284Z",
      updated_at: "2024-11-24T08:33:43.963Z",
      airtable_id: "recDUpCSGTMjEOaok",
      image_url:
        "https://v5.airtableusercontent.com/v3/u/35/35/1732449600000/YCu3AoSAdUsrTvrgYwMMdw/WS-GndAnVnfKBSsjUJQGB1n4H1xQJwsmYdsBoqM1K0eWI-RAi-8gaZLQmLJBZdMJctLdtS7BPEfF0VJ3OYU6WnXFTVAqAYSzvgxdsvfxwQxpG40WtGYR8zziTRFKgm-SYfI_ID8hAqmiLaHI8w89SA/Euhcn-HhU2QXLNut3t8L1TR8BD0ZkEr8s7ScsuvuOJw",
    },
    {
      id: 234,
      name: "Orašar",
      category: "Kazalište",
      location: "Zvonimirova 17 Odjel za djecu i mladež Knjižnice Medveščak",
      description:
        'Udruga LOFT održat će predstavu "Orašar" na Odjelu za djecu i mladež Knjižnice Medveščak u tri termina (5.12., 12.12. i 19.12.) za djecu stariju od pet godina.\n',
      start_datetime: "2024-12-05T17:00:00.000Z",
      end_datetime: "2024-12-19T17:00:00.000Z",
      price: "0.0",
      kid_friendly: true,
      event_url: null,
      created_at: "2024-11-23T18:08:25.301Z",
      updated_at: "2024-11-23T18:08:25.301Z",
      airtable_id: "recx5dijfLoOKdLow",
      image_url: null,
    },
    {
      id: 143,
      name: "Advent",
      category: "Razno",
      location: null,
      description:
        "Obilježite s nama blagdansko ozračje kroz kreativne radionice, koncerte i predstave u Susedgradu. Dočekat ćemo skupa sv. Nikolu, družiti se na radionicama Hrvatskih autentičnih drvenih igračaka, slušati koncert Gospel zbora i mnogo više! Veselimo se vašem dolasku!\n",
      start_datetime: "2024-12-06T17:30:00.000Z",
      end_datetime: null,
      price: null,
      kid_friendly: null,
      event_url: null,
      created_at: "2024-11-23T18:08:24.545Z",
      updated_at: "2024-11-23T18:08:24.545Z",
      airtable_id: "recbOC26FpUkI3V03",
      image_url: null,
    },
    {
      id: 167,
      name: "Radionice ukrašavanja staklenih kuglica ",
      category: "Muzeji",
      location: null,
      description:
        "I ovog Adventa, pridružite nam se na Radionicama** **ukrašavanja staklenih kuglica, pod vodstvom Petre Krhen Antonić (obrt _Katarina_). \nRadionice su namijenjene svim dobnim skupinama (djeca od 6 godina na više i odrasli). \nObavezno ponesite staru odjeću koju vam nije žao zaprljati. \n \nVrijeme održavanja:\nsubota, 7.12., od 10 do 11.30 sati \nsubota, 14.12. od 13 do 14.30 sati\n \nCijena radionice: djeca 7 eura, odrasli 10 eura\nBroj sudionika (po radionici) ograničen je na 15 osoba. Molimo da svoj dolazak obavezno najavite barem dan ranije, e-mailom na adresu [msabolic@mgz.hr](mailto:msabolic@mgz.hr) ili telefonom: 01/ 4851 361.\n",
      start_datetime: "2024-12-07T09:00:00.000Z",
      end_datetime: "2024-12-14T12:00:00.000Z",
      price: null,
      kid_friendly: true,
      event_url: null,
      created_at: "2024-11-23T18:08:24.748Z",
      updated_at: "2024-11-23T18:08:24.748Z",
      airtable_id: "recfpXQJPxbJvBJUv",
      image_url: null,
    },
    {
      id: 142,
      name: "sv.nikola",
      category: "Kazalište",
      location: "Park Stara Trešnjevka 1, Zagreb",
      description:
        "Ne propustite pogledati predstavu Kazališta Prijatelj u kojoj vještica Zloćkoslava pokušava ukrasti Božić. U božićno vrijeme, kao što svi vrlo dobro znamo, Sveti Nikola luta svijetom i razveseljava djecu pričom i poklonima. Ponekad malo zaluta, ode na krivi kontinent, ali na kraju uvijek uspije svima donijeti radost i veselje. Ovaj put, u ovoj predstavi, naletjet će na opasnog neprijatelja – Zloćkoslavu. Ona se ne zadovoljava jednim poklonom, ona hoće sve poklone koje Sveti Nikola donosi dobroj djeci diljem svijeta. Ali, naravno, božićna predstava mora završiti sretno. Zato se pojavljuje dječak Milivoj Štreber koji će imati hrabrosti suprotstaviti se Zloćkoslavi i pobijediti njezino čaranje. On će ne samo uspjeti osloboditi Svetog Nikolu, već će i Zloćkicu uvjeriti da smisao Božića nije u gomilanju poklona nego u ozračju dobrote i mira koju on donosi u naša srca. Predstava je za djecu stariju od 3 godine. Predstava se odvija u sklopu programa **Kazalište za sve** te s toga ima promotivnu cijenu ulaznice.\n",
      start_datetime: "2024-12-07T10:00:00.000Z",
      end_datetime: "2024-12-07T10:30:00.000Z",
      price: "3.95",
      kid_friendly: true,
      event_url: "https://cekate.hr/program/sveti-nikola-i-zlockoslava-2/",
      created_at: "2024-11-23T18:08:24.537Z",
      updated_at: "2024-11-24T08:33:44.301Z",
      airtable_id: "recb67C9PsEIbojJ5",
      image_url:
        "https://v5.airtableusercontent.com/v3/u/35/35/1732449600000/ys15ohnfTEPwSD45Lvmm-Q/-_D2E7B6d-XVClaG8AYaWb8d9CryjdyPYFkKZJo_1meNiUJ3h4EQZfQ7wQ0UFdemYm9Rhnu0MeLIKGt1KLkc9kj3XixF7LkZDu4rt8uAizz1UBeJtpWWPhKwOJXYSROh85vbfqV9V8E-7lCc2wtDKA/snfVHkZGu0bdGLsbKStUioDwIT0pDg1wPg-jRJI-Q2o",
    },
    {
      id: 38,
      name: "Radionice izrade paprenjaka ",
      category: "Muzeji",
      location: null,
      description:
        "Pridružite nam se na Radionicama izrade paprenjaka koje će voditi Sanja Paprenjak (tvrtka _Paprenjak_). \nObavezno ponesite pregaču i/ili staru odjeću koju vam nije žao zaprljati. \nVrijeme održavanja:\n\\- Radionica namijenjena odraslima (broj sudionika ograničen na 8):\nsubota, 7. 12., od 12.30 do 14 sati. \nCijena radionice (po osobi): 10 eura\n \nRadionica namijenjena djeci uzrasta od 6 do 12 godina (broj sudionika ograničen na 12):\nsubota, 14. 12., od 10.30 do 12 sati. \nCijena radionice (po osobi): 7 eura\n\nZbog ograničenog broja sudionika, molimo da svoj dolazak obavezno najavite barem dan ranije, e-mailom na adresu [msabolic@mgz.hr](mailto:msabolic@mgz.hr) ili telefonom: 01/ 4851 361.\n",
      start_datetime: "2024-12-07T11:30:00.000Z",
      end_datetime: "2024-12-14T09:30:00.000Z",
      price: null,
      kid_friendly: true,
      event_url: null,
      created_at: "2024-11-23T18:08:23.167Z",
      updated_at: "2024-11-23T18:08:23.167Z",
      airtable_id: "recB82x0AwFT14vV1",
      image_url: null,
    },
    {
      id: 45,
      name: "Adventski koncerti Zagrebačkih solista",
      category: "Muzeji",
      location: null,
      description:
        "Nezaobilazan dio zagrebačkih adventskih događanja, tradicionalni adventski koncerti Zagrebačkih solista u Muzeju grada Zagreba, pomno odabranim blagdanskim glazbenim poslasticama iz hrvatskih i svjetskih kajdanki i ove će vas godine na najljepši način uvesti u čaroliju Božića.\nUlaz besplatan.\n",
      start_datetime: "2024-12-08T10:00:00.000Z",
      end_datetime: "2024-12-15T11:00:00.000Z",
      price: "0.0",
      kid_friendly: true,
      event_url: null,
      created_at: "2024-11-23T18:08:23.259Z",
      updated_at: "2024-11-23T18:08:23.259Z",
      airtable_id: "recDEwjqyq0MtSuwp",
      image_url: null,
    },
    {
      id: 25,
      name: "Božić u srcu ",
      category: "Razno",
      location:
        "Knjižnica Kajfešov brijeg, Ulica grada Gualda Tadina 4, 10000 Zagreb",
      description: "Radionica izrade božićnih ukrasa.\n",
      start_datetime: "2024-12-11T16:30:00.000Z",
      end_datetime: "2024-12-11T18:30:00.000Z",
      price: null,
      kid_friendly: null,
      event_url: null,
      created_at: "2024-11-23T18:08:23.042Z",
      updated_at: "2024-11-23T18:08:23.042Z",
      airtable_id: "rec6nNEWZRizVRaWB",
      image_url: null,
    },
    {
      id: 176,
      name: "Božićna želja",
      category: "Kazalište",
      location: null,
      description:
        "Poetična obiteljska priča prožeta božićnim duhom govori o pravim vrijednostima u životu, ljubavi, zajedništvu i prijateljstvu.\n\nDora (8) i Luka (15) su brat i sestra koje žive s tatom i mamom koji “non-stop” rade, sužbeno putuju ili su na telefonu. Luka je u pubertetu i ne zanima ga ništa osim blagodati 21. stoljeća: interneta, fejsa, twittera, instagrama.. Sanja o pjevačkoj karijeri. Dora je usamljena i u školi i kod kuće, te uoči Božića sanja svoje prijatelje vile i vilenjake u nadi da će joj pomoći barem jedan dan u godini, na Božić, okupiti obitelj, kako sama kaže, oko “okićenog” bora ispod kojeg ne mora biti ni jedan jedini dar za nju, osim tate, mame i Luke. U zbrci tatinih telefonskih poziva, maminih otkazanih letova, svađica između Luke i Dore, isprepliću se sjećanja na neka druga vremena kada je obitelj bila zajedno, na dan kada je Dora kao zamotuljak stigla kući iz bolnice, na igre brata i sestre koja je ispunjavala kuću veselim smijehom.\n\nHoće li se Dorina obitelj okupiti ovoga Božića ispred okićenoga bora? Hoće li tinejdžer Luka potajno priznati da mu je omiljeni film Sam u kući i da postoji Djed Mraz preostaje Vam da otkrijete u našoj predstavi koja će razveseliti djecu, a roditelje ponovno vratiti u mladost i prisjetiti što znači pravi BOŽIĆ!\n",
      start_datetime: "2024-12-15T10:00:00.000Z",
      end_datetime: "2024-12-15T10:50:00.000Z",
      price: "6.0",
      kid_friendly: true,
      event_url: "https://zar-ptica.hr/predstava/predstave/bozicna-zelja/",
      created_at: "2024-11-23T18:08:24.840Z",
      updated_at: "2024-11-24T08:33:44.745Z",
      airtable_id: "rechAvBXdmjMm0qAy",
      image_url:
        "https://v5.airtableusercontent.com/v3/u/35/35/1732449600000/Ep3_Q8oWfUpJ34Ir-UdFWA/exqjtMMuNb_kRcp972fko9Mep23GqkW-wwm3oykw14d8tndFM-U6EpzofixMOLj8cs5jqKPueGWMjrbeH7y9Qp1FCxhNOXIWrvllV_vtDTAs8uLQKLBRi2wA9cCYebWQrm5Y47X0xJa4fCdrdCc_0A/mxnXb2Xidv0sRXi25yAqqaPNOR3zcseT96RMRVTFHd8",
    },
    {
      id: 168,
      name: "BOŽIĆ KOD ZIMOGROZNIH",
      category: "Glazba",
      location: null,
      description:
        "Bajka o spašavanju Božića, o izlazu iz zemlje\notuđenosti i povratka starih vrijednosti. Ovo je\npriča o promjeni srca, o malim gestama koje\nmijenjaju svijet.\n",
      start_datetime: "2024-12-16T09:00:00.000Z",
      end_datetime: null,
      price: "10.0",
      kid_friendly: true,
      event_url:
        "https://www.zgf.hr/hr/koncertni-kalendar/bozic-kod-zimogroznih-kresimir-batinic-dirigent-kd-vatroslav-lisinski_2024-12-16_10-00/",
      created_at: "2024-11-23T18:08:24.757Z",
      updated_at: "2024-11-24T08:33:44.369Z",
      airtable_id: "recfxM3Wla3TFcNl4",
      image_url:
        "https://v5.airtableusercontent.com/v3/u/35/35/1732449600000/wjED9o7THBRro_FOqfx9WA/fX5ES0PRfKtd4z_9W-l_7wX9dYspaC3bKrT3hNiQcEdxhD-gqG2tJkIGpuTeWlHeP8sk53cPbv8XM9RMa2b-9mcSHs6xKVtXRUUS7zs6nkYG_Wv2Z4_ihRsI325sk7gPhTk_n1PxZwDIgyshgKGwwA/BRBiaAvqFnB9vcOTRMqA08BYx5KcO4CVaEtGZGy46l8",
    },
    {
      id: 170,
      name: "Božićna izložba",
      category: "Likovna umjetnost",
      location: "Knjižnica Sesvete, Trg D. Domjanića 6",
      description:
        "Izložba likovnih radova djece polaznika DV Sesvete posvećenih Božiću.\n",
      start_datetime: "2024-12-16T12:59:00.000Z",
      end_datetime: "2025-01-12T12:59:00.000Z",
      price: "0.0",
      kid_friendly: true,
      event_url: null,
      created_at: "2024-11-23T18:08:24.775Z",
      updated_at: "2024-11-23T18:08:24.775Z",
      airtable_id: "recgIGRpLBfBafpW6",
      image_url: null,
    },
    {
      id: 19,
      name: 'Radionice "Jaslice pod zvijezdama" ',
      category: "Muzeji",
      location: null,
      description:
        "U subotu, 21. 12., pridružite nam se na radionicama izrade jaslica, _Jaslice pod zvijezdama_, koje će voditi Perica Novosel (Udruga prijatelja hrvatskih božićnih jaslica).\nRadionice su namijenjene svim dobnim skupinama (djeca od 6 godina na više i odrasli). \n \nVrijeme održavanja (dva termina):\nsubota, 21.12., od 10 do 12 sati i od 12.30 do 14.30 sati \nCijena radionice: djeca 7 eura, odrasli 10 eura\n \nBroj sudionika (po radionici) ograničen je na 15 osoba. Zbog ograničenog broja sudionika, molimo da svoj dolazak obavezno najavite barem dan ranije, e-mailom na adresu [msabolic@mgz.hr](mailto:msabolic@mgz.hr) ili telefonom: 01/ 4851 361.\n",
      start_datetime: "2024-12-21T09:00:00.000Z",
      end_datetime: "2024-12-21T11:30:00.000Z",
      price: null,
      kid_friendly: true,
      event_url: null,
      created_at: "2024-11-23T18:08:22.990Z",
      updated_at: "2024-11-23T18:08:22.990Z",
      airtable_id: "rec5hY4oqOGXT5pqj",
      image_url: null,
    },
  ],
};
